spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432/cybergarden}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true

springdoc:
  api-docs:
    path: /consumify/v3/api-docs
  swagger-ui:
    path: /docs