export { HomeTab } from './home-tab'
export { LoginTab } from './login-tab'
export { CatalogTab } from './catalog-tab'
export { ProductTab } from './product-tab'
export { ProfileTab } from './profile-tab'
export * from './home-tab-blocks'